listen_addresses = '*'

shared_buffers = 512MB
effective_cache_size = 1536MB
maintenance_work_mem = 128MB
work_mem = 32MB

wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB

log_min_messages = warning
log_min_error_statement = error
